### ISSUE TITLE
Problem while running example.

### ISSUE THREAD

**Issue by OOF-dura** [bstellato/mlopt#13]
```
Traceback (most recent call last):
  File "/media/frank/easystore/Code/P2S/mlopt/test.py", line 2, in <module>
    from mlopt.sampling import uniform_sphere_sample
  File "/media/frank/easystore/Code/P2S/mlopt/mlopt/__init__.py", line 1, in <module>
    from mlopt.optimizer import Optimizer
  File "/media/frank/easystore/Code/P2S/mlopt/mlopt/optimizer.py", line 4, in <module>
    from mlopt.learners import LEARNER_MAP, installed_learners
  File "/media/frank/easystore/Code/P2S/mlopt/mlopt/learners/__init__.py", line 1, in <module>
    from mlopt.learners.pytorch.pytorch import PytorchNeuralNet
  File "/media/frank/easystore/Code/P2S/mlopt/mlopt/learners/pytorch/pytorch.py", line 2, in <module>
    import mlopt.learners.pytorch.settings as pts
AttributeError: module 'mlopt' has no attribute 'learners'

Process finished with exit code 1

```

**Comment by Chen0917** [comment]
Same issue here. It seems this is relevant to the way to import sub-packages with absolute path info. Would the author consider experimenting on a fresh Python without existing original package code?

Thanks!

**Comment by Chen0917** [comment]
> ```
> Traceback (most recent call last):
>   File "/media/frank/easystore/Code/P2S/mlopt/test.py", line 2, in <module>
>     from mlopt.sampling import uniform_sphere_sample
>   File "/media/frank/easystore/Code/P2S/mlopt/mlopt/__init__.py", line 1, in <module>
>     from mlopt.optimizer import Optimizer
>   File "/media/frank/easystore/Code/P2S/mlopt/mlopt/optimizer.py", line 4, in <module>
>     from mlopt.learners import LEARNER_MAP, installed_learners
>   File "/media/frank/easystore/Code/P2S/mlopt/mlopt/learners/__init__.py", line 1, in <module>
>     from mlopt.learners.pytorch.pytorch import PytorchNeuralNet
>   File "/media/frank/easystore/Code/P2S/mlopt/mlopt/learners/pytorch/pytorch.py", line 2, in <module>
>     import mlopt.learners.pytorch.settings as pts
> AttributeError: module 'mlopt' has no attribute 'learners'
> 
> Process finished with exit code 1
> ```

It's the circular import. Check this commit (https://github.com/laf070810/mlopt.git). Many thanks to @laf070810 !
